require_relative "jekyll-open-sdg-plugins/version"
require_relative "jekyll-open-sdg-plugins/site_configuration"
require_relative "jekyll-open-sdg-plugins/validate_site_config"
require_relative "jekyll-open-sdg-plugins/fetch_remote_data"
require_relative "jekyll-open-sdg-plugins/translate_key"
require_relative "jekyll-open-sdg-plugins/translate_date"
require_relative "jekyll-open-sdg-plugins/translate_metadata_field"
require_relative "jekyll-open-sdg-plugins/create_indicators"
require_relative "jekyll-open-sdg-plugins/create_goals"
require_relative "jekyll-open-sdg-plugins/create_pages"
require_relative "jekyll-open-sdg-plugins/sdg_variables"
require_relative "jekyll-open-sdg-plugins/search_index"
require_relative "jekyll-open-sdg-plugins/validate_indicator_config"
require_relative "jekyll-open-sdg-plugins/metadata_schema_to_config"
require_relative "jekyll-open-sdg-plugins/backwards_compatibility"
require_relative "jekyll-open-sdg-plugins/meta_tags"
require_relative "jekyll-open-sdg-plugins/routes"

module JekyllOpenSdgPlugins
end
